"""Tailwind theme emitter — DesignTokens -> tailwind.config.js (Layer 3).

The page's deduplicated design tokens (colors / spacing / type / radii / shadows)
are mapped into a Tailwind ``theme.extend`` block. Codegen then references these
by their token *name* (e.g. ``bg-surface``, ``gap-s2``) so the output is
utility-class-driven instead of inline-CSS-driven — killing R1/R2/R3 at the root.

Pure / deterministic. No I/O, no LLM.
"""

from __future__ import annotations

import json
from typing import Dict

from core.ir.schema import DesignTokens

# Map a DesignTokens attribute to its Tailwind ``theme.extend`` key.
_THEME_KEYS = [
    ("colors", "colors"),
    ("space", "spacing"),
    ("type", "fontFamily"),
    ("radius", "borderRadius"),
    ("shadow", "boxShadow"),
]


def _emit_map(values: Dict[str, str], indent: str) -> str:
    """Render a name->value map as JS object entries, JSON-escaped values."""
    if not values:
        return ""
    lines = []
    for name, value in values.items():
        # json.dumps gives a safe, quoted JS string literal for both key + value.
        key = json.dumps(str(name))
        val = json.dumps(str(value))
        lines.append(f"{indent}{key}: {val},")
    return "\n".join(lines)


def emit_tailwind_theme(tokens: DesignTokens) -> str:
    """Return a ``tailwind.config.js`` string with a token-driven theme.extend.

    Each token map becomes a Tailwind theme group so its names resolve to
    utility classes (``colors.ink`` -> ``text-ink``/``bg-ink``,
    ``spacing.s2`` -> ``gap-s2``/``p-s2``, etc.).
    """
    groups = []
    for attr, theme_key in _THEME_KEYS:
        values: Dict[str, str] = getattr(tokens, attr) or {}
        body = _emit_map(values, indent=" " * 8)
        if body:
            groups.append(f"      {theme_key}: {{\n{body}\n      }},")
        else:
            groups.append(f"      {theme_key}: {{}},")

    extend_body = "\n".join(groups)

    return (
        "/** @type {import('tailwindcss').Config} */\n"
        "// GENERATED by core/codegen/tailwind_theme.py from the page's DesignTokens.\n"
        "// Edit the IR token table, not this file.\n"
        "module.exports = {\n"
        '  content: ["./index.html", "./src/**/*.{js,jsx,ts,tsx}"],\n'
        "  theme: {\n"
        "    extend: {\n"
        f"{extend_body}\n"
        "    },\n"
        "  },\n"
        "  plugins: [],\n"
        "};\n"
    )
